### ISSUE TITLE
The item reference is not passed. 

### ISSUE THREAD

**Issue by sibalonat** [eliottvincent/vue3-sortablejs#2]
So so far, after some reading, I choose to use this plugin for one of my projects. It was working fine until I encountered something I probably will need some reworking or at least you can give me some direction about this. 
So, in vue draggable, I know you can reference the item in v-for, in this plugin because the instantiation begins before v-for, it's impossible to make a reference of the element data it's changing the order. Do you know a way to bypass that?

**Comment by eliottvincent** [comment]
Hey! You have access to the index of the item triggering the change in the `end` event: https://github.com/eliottvincent/vue3-sortablejs#order-mutation
